/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppRedeemRouteImport } from './routes/_app.redeem'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppProfileUsernameRouteImport } from './routes/_app.profile.$username'
import { Route as AppProfileUsernameEditRouteImport } from './routes/_app.profile.$username.edit'
import { Route as AppPostUserIdPostIdRouteImport } from './routes/_app.post.$userId.$postId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRedeemRoute = AppRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameEditRoute = AppProfileUsernameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileUsernameRoute,
} as any)
const AppPostUserIdPostIdRoute = AppPostUserIdPostIdRouteImport.update({
  id: '/post/$userId/$postId',
  path: '/post/$userId/$postId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create': typeof AppCreateRoute
  '/notifications': typeof AppNotificationsRoute
  '/redeem': typeof AppRedeemRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/profile/$username': typeof AppProfileUsernameRouteWithChildren
  '/post/$userId/$postId': typeof AppPostUserIdPostIdRoute
  '/profile/$username/edit': typeof AppProfileUsernameEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create': typeof AppCreateRoute
  '/notifications': typeof AppNotificationsRoute
  '/redeem': typeof AppRedeemRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/profile/$username': typeof AppProfileUsernameRouteWithChildren
  '/post/$userId/$postId': typeof AppPostUserIdPostIdRoute
  '/profile/$username/edit': typeof AppProfileUsernameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/redeem': typeof AppRedeemRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/profile/$username': typeof AppProfileUsernameRouteWithChildren
  '/_app/post/$userId/$postId': typeof AppPostUserIdPostIdRoute
  '/_app/profile/$username/edit': typeof AppProfileUsernameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/create'
    | '/notifications'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/profile/$username'
    | '/post/$userId/$postId'
    | '/profile/$username/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/create'
    | '/notifications'
    | '/redeem'
    | '/search'
    | '/settings'
    | '/'
    | '/profile/$username'
    | '/post/$userId/$postId'
    | '/profile/$username/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/create'
    | '/_app/notifications'
    | '/_app/redeem'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/'
    | '/_app/profile/$username'
    | '/_app/post/$userId/$postId'
    | '/_app/profile/$username/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/redeem': {
      id: '/_app/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof AppRedeemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$username/edit': {
      id: '/_app/profile/$username/edit'
      path: '/edit'
      fullPath: '/profile/$username/edit'
      preLoaderRoute: typeof AppProfileUsernameEditRouteImport
      parentRoute: typeof AppProfileUsernameRoute
    }
    '/_app/post/$userId/$postId': {
      id: '/_app/post/$userId/$postId'
      path: '/post/$userId/$postId'
      fullPath: '/post/$userId/$postId'
      preLoaderRoute: typeof AppPostUserIdPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProfileUsernameRouteChildren {
  AppProfileUsernameEditRoute: typeof AppProfileUsernameEditRoute
}

const AppProfileUsernameRouteChildren: AppProfileUsernameRouteChildren = {
  AppProfileUsernameEditRoute: AppProfileUsernameEditRoute,
}

const AppProfileUsernameRouteWithChildren =
  AppProfileUsernameRoute._addFileChildren(AppProfileUsernameRouteChildren)

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRedeemRoute: typeof AppRedeemRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRouteWithChildren
  AppPostUserIdPostIdRoute: typeof AppPostUserIdPostIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRedeemRoute: AppRedeemRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProfileUsernameRoute: AppProfileUsernameRouteWithChildren,
  AppPostUserIdPostIdRoute: AppPostUserIdPostIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
